version: '3.8'

services:

  nginx:
    image: docker.arvancloud.ir/nginx:latest
    container_name: nginx_reverse_proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - "80:80"
